config/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", home, name="home"),
    path("employees/", include("employees.urls")),
    path("daily_reports/", include("daily_reports.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

daily_reports/urls.py
from django.urls import path

from .views import (
    DailyReportCommentCreateView,
    DailyReportCreateView,
    DailyReportDeleteView,
    DailyReportDetailView,
    DailyReportEditView,
    DailyReportListView,
    daily_report_delete_confirm,
)

urlpatterns = [
    path(
        "<int:pk>/comment/new/",
        DailyReportCommentCreateView.as_view(),
        name="daily_report_comment_new",
    ),
    path(
        "<int:pk>/detail/",
        DailyReportDetailView.as_view(),
        name="daily_report_detail",
    ),
    path("", DailyReportListView.as_view(), name="daily_report_index"),
    path("new/", DailyReportCreateView.as_view(), name="daily_report_new"),
    path("<int:pk>/edit/", DailyReportEditView.as_view(), name="daily_report_edit"),
    path(
        "<int:pk>/delete_confirm/",
        daily_report_delete_confirm,
        name="daily_report_delete_confirm",
    ),
    path(
        "<int:pk>/delete/", DailyReportDeleteView.as_view(), name="daily_report_delete"
    ),
]

daily_reports/models.py
from django.db import models
from employees.models import Employee


# Create your models here.


class DailyReport(models.Model):
    employee_code = models.ForeignKey(Employee, on_delete=models.CASCADE)
    job_description = models.TextField(max_length=2000)
    reported_on = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Employee: {self.employee_code.name}, Date: {self.reported_on}, Content: {self.job_description[:7]}, CreatedAt: {self.created_at}, UpdatedAt: {self.updated_at}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["employee_code", "reported_on"], name="uq_daily_report_01"
            )
        ]


class DailyReportComment(models.Model):
    employee_code = models.ForeignKey(Employee, on_delete=models.CASCADE)
    daily_report_code = models.ForeignKey(DailyReport, on_delete=models.CASCADE)
    comment = models.TextField(max_length=2000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Commenter: {self.employee_code.name}, Employee: {self.daily_report_code.employee_code.name}, Date: {self.daily_report_code.reported_on}, Comment: {self.comment[:7]}, CreatedAt: {self.created_at}, UpdatedAt: {self.updated_at}"

daily_reports/forms.py
from django import forms

from .models import DailyReport, DailyReportComment


# 日報コメントフォーム
class DailyReportCommentForm(forms.ModelForm):
    comment = forms.CharField(
        required=False,  # Django の標準必須バリデーションを無効化
        widget=forms.Textarea(attrs={"placeholder": "コメントを入力してください"}),
        initial="",
    )

    class Meta:
        model = DailyReportComment
        fields = ["comment"]

    # 外部からemployeeとdaily_reportをフォームのインスタンスから受け取れる設定
    def __init__(self, *args, **kwargs):
        self.employee = kwargs.pop("employee", None)
        self.daily_report = kwargs.pop("daily_report", None)
        super().__init__(*args, **kwargs)

    # コメントの文字数のバリデーション
    def clean_comment(self):
        comment = self.cleaned_data.get("comment", "").strip()  # 前後の空白を削除
        length = len(comment)
        if length < 1:
            raise forms.ValidationError(
                "コメントは1文字以上2000文字以内で入力してください。"
            )
        if length > 2000:
            raise forms.ValidationError(
                f"コメントは2000文字以内で入力してください。（現在の文字数: {length}）"
            )
        return comment

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.employee:
            instance.employee_code = self.employee
        if self.daily_report:
            instance.daily_report_code = self.daily_report
        if commit:
            instance.save()
        return instance


# 日報一覧画面 日付範囲検索
class DailyReportSearchForm(forms.Form):
    start_date = forms.DateField(
        required=False, widget=forms.DateInput(attrs={"type": "date"}), label="いつから"
    )
    end_date = forms.DateField(
        required=False, widget=forms.DateInput(attrs={"type": "date"}), label="いつまで"
    )
    keyword = forms.CharField(required=False, label="キーワード")


# 日報新規登録画面
class DailyReportForm(forms.ModelForm):
    class Meta:
        model = DailyReport
        fields = ["employee_code", "reported_on", "job_description"]
        labels = {
            "job_description": "業務内容",
            "reported_on": "日付",
        }
        widgets = {
            "employee_code": forms.HiddenInput(),
            "reported_on": forms.DateInput(
                attrs={"type": "date"}
            ),  # カレンダー入力にする
        }

    # def clean_job_description(self):
    #      job_description = self.cleaned_data.get("job_description")
    #      if len(job_description) > 2000:
    #         raise forms.ValidationError("業務内容は2000文字以内で入力してください。")
    #      return job_description

    def save(self, commit=True):
        daily_report = super().save(commit=False)
        if commit:
            daily_report.save()
        return daily_report


# 日報編集画面
class DailyReportEditForm(forms.ModelForm):
    job_description = forms.CharField(
        required=False,  # Django の標準必須バリデーションを無効化
        widget=forms.Textarea(),
    )

    class Meta:
        model = DailyReport
        fields = ["job_description"]
        labels = {"job_description": "業務内容"}

        # 業務内容の文字数のバリデーション

    def clean_job_description(self):
        job_description = self.cleaned_data.get(
            "job_description", ""
        ).strip()  # 前後の空白を削除
        length = len(job_description)
        if length < 1:
            raise forms.ValidationError(
                "業務内容は1文字以上2000文字以内で入力してください。"
            )
        if length > 2000:
            raise forms.ValidationError(
                f"業務内容は2000文字以内で入力してください。（現在の文字数: {length}）"
            )
        return job_description

daily_reports/views.py
from datetime import datetime

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.timezone import make_aware
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import (
    DailyReportCommentForm,
    DailyReportEditForm,
    DailyReportForm,
    DailyReportSearchForm,
)
from .models import DailyReport, DailyReportComment, Employee


# 日報コメント新規作成画面
@method_decorator(login_required, name="dispatch")
class DailyReportCommentCreateView(CreateView):
    model = DailyReportComment
    template_name = "daily_reports/daily_reports_comment_new.html"
    form_class = DailyReportCommentForm

    def form_valid(self, form):
        daily_report = get_object_or_404(DailyReport, id=self.kwargs.get("pk"))
        employee = Employee.objects.get(user=self.request.user)

        # formのインスタンスにemployeeとdaily_reportを設定
        form.instance.employee_code = employee
        form.instance.daily_report_code = daily_report
        return super().form_valid(form)

    # テンプレートで利用するためのコンテキストの設定
    def get_context_data(self, **kwargs):
        daily_report = get_object_or_404(DailyReport, id=self.kwargs.get("pk"))

        context = super().get_context_data(**kwargs)
        context["employee_name"] = daily_report.employee_code.name
        context["reported_on"] = daily_report.reported_on
        context["daily_report"] = daily_report
        context["job_description"] = daily_report.job_description
        return context

    # 成功時のURLをpkから設定
    def get_success_url(self):
        return reverse("daily_report_detail", kwargs={"pk": self.kwargs.get("pk")})


# 日報新規登録
@method_decorator(login_required, name="dispatch")
class DailyReportCreateView(CreateView):
    model = DailyReport
    form_class = DailyReportForm
    template_name = "daily_reports/daily_report_new.html"

    def form_valid(self, form):
        if not form.instance.reported_on:
            form.instance.reported_on = timezone.now().date()  # 今日の日付を設定
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial['reported_on'] = timezone.now().date()  # 今日の日付を初期値に設定
        initial["employee_code"] = Employee.objects.get(user=self.request.user)
        initial["reported_on"] = timezone.now().date()  # 今日の日付を初期値に設定
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["employee_code"] = Employee.objects.get(user=self.request.user)
        return context

    def get_success_url(self):
        return reverse(
            "daily_report_index",
        )


# 日報一覧画面 検索機能あり
@method_decorator(login_required, name="dispatch")
class DailyReportListView(ListView):
    model = DailyReport
    template_name = "daily_reports/daily_report_list.html"
    context_object_name = "daily_reports"
    ordering = "-reported_on"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["employee"] = Employee.objects.select_related("employee_code").values(
            "name"
        )
        context["form"] = DailyReportSearchForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = DailyReportSearchForm(self.request.GET)

        if form.is_valid():
            keyword = form.cleaned_data.get("keyword")
            start_date = form.cleaned_data.get("start_date")
            end_date = form.cleaned_data.get("end_date")

            # 検索
            if keyword:
                queryset = queryset.filter(
                    job_description__icontains=keyword
                ) | queryset.filter(employee_code__name__icontains=keyword)
            if start_date and end_date:
                queryset = queryset.filter(
                    reported_on__range=(
                        make_aware(datetime.combine(start_date, datetime.min.time())),
                        make_aware(datetime.combine(end_date, datetime.max.time())),
                    )
                )
            elif start_date:
                queryset = queryset.filter(
                    reported_on__gte=make_aware(
                        datetime.combine(start_date, datetime.min.time())
                    )
                )
            elif end_date:
                queryset = queryset.filter(
                    reported_on__lte=make_aware(
                        datetime.combine(end_date, datetime.max.time())
                    )
                )
            return queryset


# 日報編集画面
@method_decorator(login_required, name="dispatch")
class DailyReportEditView(UpdateView):
    model = DailyReport
    form_class = DailyReportEditForm
    template_name = "daily_reports/daily_report_edit.html"

    # success_url = reverse_lazy('daily_report_detail', kwargs={"pk": self.kwargs.get("pk")})
    def get_context_data(self, **kwargs):
        daily_report = get_object_or_404(DailyReport, id=self.kwargs.get("pk"))

        context = super(DailyReportEditView, self).get_context_data(**kwargs)
        context["message_type"] = "edit"
        context["obj"] = DailyReport.objects.get(id=self.kwargs["pk"])
        context["employee_name"] = daily_report.employee_code.name
        context["reported_on"] = daily_report.reported_on
        return context

    # 成功時のURLをpkから設定
    def get_success_url(self):
        return reverse("daily_report_detail", kwargs={"pk": self.kwargs.get("pk")})


# 日報詳細画面
@method_decorator(login_required, name="dispatch")
class DailyReportDetailView(DetailView):
    model = DailyReport
    template_name = "daily_reports/daily_report_detail.html"
    context_object_name = "daily_report"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["employee"] = Employee.objects.select_related("employee_code").values(
            "name"
        )
        # FKの無い側からある側にモデルを逆参照
        context["obj"] = DailyReport.objects.get(id=self.kwargs["pk"])
        return context


# 日報削除確認画面
@login_required
def daily_report_delete_confirm(request, pk):
    daily_report = get_object_or_404(DailyReport, pk=pk)
    return render(
        request,
        "daily_reports/daily_report_delete_confirm.html",
        {"daily_report": daily_report},
    )


# 日報削除
@method_decorator(staff_member_required, name="dispatch")
class DailyReportDeleteView(DeleteView):
    model = DailyReport
    template_name = "daily_reports/daily_report_delete_confirm.html"
    success_url = reverse_lazy("daily_report_index")

daily_reports/templates/daily_reports/daily_report_delete_confirm.html
{% extends "base.html" %}

{% block title %}削除確認画面{% endblock title %}

{% block content %}
<h1>削除の確認</h1>
<p>
    以下の日報を削除します。よろしいですか？
</p>
<ul>

    <li>
        名前：{{ daily_report.employee_code.name }}
    </li>
    <li>
        日付：{{ daily_report.reported_on}}
    </li>
</ul>
<form method="POST" action="{% url 'daily_report_delete' daily_report.pk %}">
  {% csrf_token %}
  {% comment %} 削除ボタンは赤色 {% endcomment %}
  <button type="submit" class="btn btn-danger">削除</button>
  <a href="{% url 'daily_report_detail' daily_report.pk %}">キャンセル</a>
</form>
{% endblock content %}

daily_reports/templates/daily_reports/daily_report_detail.html
{% extends 'base.html' %}

{% block title %}日報詳細画面{% endblock %}

{% block content %}
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <section class="career">
        <h1 class="text-center mb-4">日報の詳細画面</h1>
        <div class="table-responsive">
          <table class="table table-bordered">
            <tr>
              <th class="table-primary" style="width: auto;">名前</th>
              <td style="word-wrap: break-word; white-space: normal;">
                {{ object.employee_code.name }}
              </td>
            </tr>
            <tr>
              <th class="table-primary" style="width: auto;">日付</th>
              <td>{{ object.reported_on|date:"Y/m/d" }}</td>
            </tr>
            <tr>
              <th class="table-primary" style="width: auto;">更新日時</th>
              <td>{{ object.updated_at }}</td>
            </tr>
            <tr>
              <th class="table-primary" style="width: auto;">業務内容</th>
              <td style="word-wrap: break-word; white-space: normal;">
                {{ object.job_description|linebreaksbr }}
              </td>
            </tr>
          </table>
        </div>
      </section>

      <div class="d-flex justify-content-between mt-4">
        {% com = obj.dailyreport_set.all %}
        {% if object.employee_code.name == com.username %}
          <a href="{% url 'daily_report_edit' daily_report.pk %}" class="btn btn-outline-primary">編集</a>
          <a href="{% url 'daily_report_delete_confirm' daily_report.pk %}" class="btn btn-outline-danger">削除</a>
        {% endif %}
      </div>

      <section>
        <h2 class="mt-4 text-center">コメント一覧</h2>
        <div class="table-responsive">
          <table class="table table-striped">
            <tbody>
              {% for com in obj.dailyreportcomment_set.all %}
              <tr>
                <th class="table-secondary" style="width: auto;">コメント作成者</th>
                <td>{{ com.employee_code.name }}</td>
              </tr>
              <tr>
                <th class="table-secondary" style="width: auto;">更新日時</th>
                <td>{{ com.updated_at }}</td>
              </tr>
              <tr>
                <th class="table-secondary" style="width: auto;">コメント</th>
                <td style="word-wrap: break-word; white-space: normal;">
                  {{ com.comment }}
                </td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="2" class="text-muted text-center">まだコメントはありません。</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </section>

      <div class="d-flex justify-content-between mt-4">
        <a href="{% url 'daily_report_index' %}" class="btn btn-outline-secondary">戻る</a>
        <a href="{% url 'daily_report_comment_new' daily_report.pk %}" class="btn btn-outline-success">コメントする</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

daily_reports/templates/daily_reports/daily_report_edit.html
{% extends 'base.html' %}

{% block title %}日報の編集{% endblock title %}

{% block content %}
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
        <h1>日報の更新</h1>

        <div class="container">
          <div class="row">
              <div class="col-md-6 d-flex align-items-center">
                  <strong>投稿者: </strong> <span class="ms-2">{{ employee_name }}</span>
              </div>
              <div class="col-md-6 text-md-end text-start">
                  <strong>日付: </strong> <span>{{ reported_on|date:"Y/m/d" }}</span>
              </div>
          </div>

<hr> <!-- 区切り線 -->

<form method="POST">
            <table>
              {{ form.as_table }}
            </table>
          {% csrf_token %}

          <button class="btn btn-primary mt-3" type="submit">登録</button>
          <a href="{% url 'daily_report_detail' obj.pk %}" class="btn btn-secondary mt-3">戻る</a>
      </form>
      </section>

      <section class="mt-4">
        <h2 class="text-center">コメント一覧</h2>
        <table class="table table-striped table-hover">
          <tr>
            <th class="table-secondary">コメント</th>
            <td style="word-wrap: break-word; white-space: normal;">
              {% for com in obj.dailyreportcomment_set.all %}
                <p><strong>コメント作成者:</strong> {{ com.employee_code.name }}</p>
                <p><strong>日時:</strong> {{ com.created_at }}</p>
                <p><strong>コメント:</strong> {{ com.comment }}</p>
                <hr>
              {% empty %}
                <p class="text-muted">まだコメントはありません。</p>
              {% endfor %}
            </td>
          </tr>
        </table>
      </section>
    </div>
  </div>
</div>
{% endblock %}

daily_reports/templates/daily_reports/daily_report_list.html
{% extends 'base.html' %}

{% block title %}日報一覧{% endblock %}

{% block content %}

<h1>日報一覧</h1>
{% comment %} 日報新規作成ボタン {% endcomment %}
<div class="d-flex justify-content-end">
  <a href="{% url 'daily_report_new' %}">
    <button type="submit" class="btn btn-primary float-right">新規作成</button>
    <br>
  </a>
</div>
{% comment %} 検索バー {% endcomment %}
<form class="form-inline my-2 my-lg-0" action="{% url 'daily_report_index' %}" method="GET">
  {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
</form>
{% comment %} 日報リスト {% endcomment %}
<table class="table table-striped">
  <thead>
    <tr>
      <th>日付</th>
      <th>名前</th>
      <th>業務内容</th>
    </tr>
  </thead>
  <tbody>
    {% for daily_report in daily_reports %}
    <tr>
      <td>{{ daily_report.reported_on|date:"Y/m/d" }}</td>
      <td>{{ daily_report.employee_code.name }}</td>
      <td>
        <a href="{% url 'daily_report_detail' daily_report.pk %}">
          {{ daily_report.job_description|slice:":15" }}
        </a>
      </td>
    </tr>
  {% empty %}
  <p>まだ日報はありません。</p>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

daily_reports/templates/daily_reports/daily_report_new.html
{% extends "base.html" %}

{% block title %}日報の新規登録{% endblock title %}

{% block content %}
<h1>日報新規登録フォーム</h1>
<p>名前: {{ employee_code.name }}</p>
<form method="POST" action="{% url 'daily_report_new' %}">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">登録</button>
</form>
{% endblock content %}

daily_reports/templates/daily_reports/daily_reports_comment_new.html
{% extends "base.html" %}

{% block title %}日報コメント登録{% endblock title %}

{% block content %}
<h1>日報コメント登録フォーム</h1>

<div class="container">
  <div class="row">
      <div class="col-md-6 d-flex align-items-center">
          <strong>投稿者: </strong> <span class="ms-2">{{ employee_name }}</span>
      </div>
      <div class="col-md-6 text-md-end text-start">
          <strong>日付: </strong> <span>{{ reported_on|date:"Y/m/d" }}</span>
      </div>
  </div>

  <hr> <!-- 区切り線 -->

  <div class="content mt-3">
      <p><strong>内容:</strong></p>
      <p class="formatted-text">{{ job_description|linebreaksbr }}</p>
  </div>
</div>

<form method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="{{ form.comment.id_for_label }}">コメント:</label>
    <textarea class="form-control" id="{{ form.comment.id_for_label }}" name="comment" rows="4" placeholder="コメントを入力してください">{{ form.comment.value }}</textarea>
  </div>


<!-- コメントフィールドのエラーメッセージを表示 -->
{% if form.comment.errors %}
    <div class="alert alert-danger">
        {% for error in form.comment.errors %}
            <p>{{ error }}</p>
        {% endfor %}
    </div>
{% endif %}

  <button type="submit" class="btn btn-primary mt-3">送信</button>
</form>
<a href="{% url 'daily_report_detail' daily_report.pk %}" class="btn btn-secondary mt-3">戻る</a>
{% endblock content %}